#!/bin/bash

echo "Restart InfluxDB"
service influxdb restart || echo "Failed to restart Influxdb. You have to restart Shinken to update its configuration"

echo "Restart Apache"
service apache2 restart || echo "Failed to restart Apache2. You have to restart Apache2 to update its configuration"

echo "Restart Shinken"
service shinken restart || echo "Failed to restart Shinken. You have to restart Shinken to update its configuration"

